### PR TITLE
jump_prev_fix

### PR DESCRIPTION
**Pull request by veksha**
different try. please test, @Alexey-T 
made two loops. now it's easier to read code and understand how it works on jump next and on jump prev.

### CODE REVIEW

**Comment by veksha** [comment]
it works almost ok, but i need something to improve a little. so please, wait.

**Comment by CudaText-addons** [comment]
waiting.

**Comment by veksha** [comment]
imporved accuracy.
added status message if you don't mind.

**Comment by Alexey-T** [comment]
to-apply.

**Comment by veksha** [comment]
+

**Comment by Alexey-T** [comment]
all is ready?

**Comment by veksha** [comment]
yes. works for you?

**Comment by Alexey-T** [comment]
a bug?

Screenshot from 2023-01-17 10-39-54

left side: jmp to prev - works any count of times (loops).
rt side: jmp to prev - stops on 1st match!

**Comment by Alexey-T** [comment]
(I call menuitem in Plugins)

**Comment by veksha** [comment]
on master branch - same. for you too?

**Comment by veksha** [comment]
if I add more empty lines to both files - then it's working good.

**Comment by veksha** [comment]
i think it's another issue. when difference is on very bottom, `set_caret` gets line index that is greater then line_count-1

**Comment by veksha** [comment]
if we want to insert `ee` from left to the right, we must have palce for it, so 5th line must be generated after refresh.
I think I know how to fix. but it's a different issue. I will have time later for it.

**Pull request merged**
