### PR TITLE
jump prev fix

### PR DESCRIPTION
**Pull request by veksha**
Jump to prev difference was not always working. Fixed. Also made new var "cnt", to make code cleaner.

### CODE REVIEW

**Comment by veksha** [comment]
Also, Alexei, do you agree to disable automatic selection of text when jumping to next/prev difference?

**Comment by veksha** [comment]
image
image


@Alexey-T github showing that this commit is authored by you. how is it possible? github bug? and my local repo was broken for some reason.

**Comment by Alexey-T** [comment]
github bug...

**Comment by Alexey-T** [comment]
`        i = None if to_next else cnt - 2 # second to last index is the default when going back
        if fc == 0:`

what if cnt==1? cnt-2 will be <0

**Comment by veksha** [comment]
it's ok. nothing will be broken.

```python
      elif i < 0:
            i = cnt - 1
```

tested with cnt==1, jumping forward/back is working fine from start of file, and from end of file too.

**Comment by veksha** [comment]
do you agree to also change this?

```diff
-        eds[0].set_caret(0, to[0], 0, to[1], ct.CARET_SET_ONE)
-        eds[1].set_caret(0, to[2], 0, to[3], ct.CARET_SET_ONE)
+        eds[0].set_caret(0, to[0], id=ct.CARET_SET_ONE)
+        eds[1].set_caret(0, to[2], id=ct.CARET_SET_ONE)
```

**Comment by Alexey-T** [comment]
yes, agree

**Comment by veksha** [comment]
after testing again:

changed `i = None if to_next else cnt - 2`
to `      i = None if to_next else cnt - 1`

I don't remember why i put -2 there. with -1 it actually works correct.

**Comment by veksha** [comment]
no. wait. found file where -1 is not working, but -2 is working.

**Comment by CudaText-addons** [comment]
applied. then i saw 'no wait'. reverted. now i don't have PR.

**Pull request merged**
